### ISSUE TITLE
run error?

### ISSUE THREAD

**Issue by JewsChen** [akasakaid/grassxd#1]
![1730646956521](https://github.com/user-attachments/assets/41e63be6-9142-4b44-a971-ac603a86d582)

**Comment by akasakaid** [comment]
Are you already add the proxy?

**Comment by JewsChen** [comment]
> Are you already add the proxy?

![image](https://github.com/user-attachments/assets/1f1e70fa-c263-4a0b-abbf-4ed9edbd5b60)
Is that OK? Sir
