### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by hein358** [akasakaid/grassxd#2]
Have bro you miss config.json i think

**Comment by akasakaid** [comment]
`git pull`

**Comment by hein358** [comment]
Thank

**Comment by hein358** [comment]
![Screenshot_2024-11-03-21-54-00-129_com.termux.jpg](https://github.com/user-attachments/assets/77ff4e99-bab3-480e-a2d1-29baa7793b55)

🥲

**Comment by akasakaid** [comment]
see [Proxy Format](https://github.com/akasakaid/grassxd?tab=readme-ov-file#about-proxy)

**Comment by hein358** [comment]
![Screenshot_2024-11-03-22-09-09-119_com.termux.jpg](https://github.com/user-attachments/assets/95654e6e-6c10-464a-b36e-a47ef282d3f9)

Is this working sir?

**Comment by akasakaid** [comment]
Yea
